{"name": "Prueba de geocodificación con error de API", "status": "passed", "description": "Verifica el manejo de errores de la API de geocodificación", "attachments": [{"name": "stdout", "source": "6cf80bee-152a-4faf-a575-2b840e9bd0aa-attachment.txt", "type": "text/plain"}], "start": 1747770661885, "stop": 1747770661890, "uuid": "7ea6978c-8a3a-4227-a4fb-6d895a10be75", "historyId": "50f7dfe5ebb5c3d7e147485417a7c502", "testCaseId": "50f7dfe5ebb5c3d7e147485417a7c502", "fullName": "tests.test_eco_guardian.TestGeocodificarDireccion#test_geocodificar_direccion_error", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "TestGeocodificarDireccion"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "41560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_eco_guardian"}]}