{"name": "Prueba de geocodificación con error de API", "status": "passed", "description": "Verifica el manejo de errores de la API de geocodificación", "attachments": [{"name": "stdout", "source": "10b076e7-187f-43fb-a72a-accd4574eaa0-attachment.txt", "type": "text/plain"}], "start": 1747770547391, "stop": 1747770547392, "uuid": "2df5b98f-b1fe-4b3a-840b-f24af6d00d2b", "historyId": "50f7dfe5ebb5c3d7e147485417a7c502", "testCaseId": "50f7dfe5ebb5c3d7e147485417a7c502", "fullName": "tests.test_eco_guardian.TestGeocodificarDireccion#test_geocodificar_direccion_error", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "TestGeocodificarDireccion"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "26600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_eco_guardian"}]}